IntelLabs/DyNAS-T

dynast/search/evolutionary.py
Replace `np.int` with `int` to remove warning: `DeprecationWarning: 'np.int' is a deprecated alias for the builtin 'int'.`
Read more: https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated
=> Fix NumPy's deprecated `np.int` alias for `int`

dynast/dynast_manager.py, dynast/utils/__init__.py, tests/test_utils.py
Add method to automatically handle deprecated metric names.
This will rename metrics from-to:
* `lat` to `latency`
* `acc` to `accuracy_top1` (for image classification)
* `acc` to `bleu` (for language translation)
=> Automatically handle deprecated metric names

linter.sh
This method will prefer lint packages installed within current virtual environment over system installed versions.
=> Change lint commands to be executed with python

requirements_test.txt
No real reason for these dependencies to have versions pinned. 
Also, depending on Python version, few of the pinned versions are not available.
=> Unpin versions of dependencies used in testing

dynast/cli.py, dynast/search/search_tactic.py, dynast/supernetwork/image_classification/ofa/ofa/imagenet_classification/data_providers/imagenet.py, dynast/supernetwork/image_classification/ofa/ofa_interface.py, dynast/utils/nn.py, dynast/utils/reference.py, tests/scripts/config.sh, tests/scripts/run_ofambv3_random_short.sh, tests/scripts/run_ofaresnet50_random_short.sh
- simplify `validate_classification` function
- replace `run_manager.validate` with ``validate_classification`. OFA code had a bug: when test size was specified it was using training dataloader instead of test.
- Rename `valid_size` to `test_size`, as it's more truthful and applies to wider range of datasets.
=> Update Image Classification Top1 Accuracy Method

dynast/supernetwork/machine_translation/transformer_interface.py, dynast/supernetwork/text_classification/bert_interface.py
Order of the columns should be the same as specified in `dynast/search/search_tactic.py:format_csv_header()`.
This will be restructured in a follow-up PR to avoid future mistakes.
=> Fix order of columns for TransformerLT and BERT-SST2 in CSV file

dynast/search/search_tactic.py, dynast/supernetwork/image_classification/ofa/ofa/imagenet_classification/run_manager/run_manager.py, dynast/supernetwork/image_classification/ofa/ofa/utils/pytorch_utils.py, dynast/supernetwork/image_classification/ofa/ofa_interface.py
By default OFA prints whole model architecture. This change adds an option to tune verbosity in OFA and by default sets it to disabled.
=> Add verbosity option to OFA

pyproject.toml, tests/checks/helpers.py
mypy will fail if DyNAS-T build directory is present. With this patch mypy will ignore any build-related directories.
license check should not report findings in `build` dir.
=> Add ignore dirs to mypy

dynast/cli.py, dynast/search/search_tactic.py, dynast/supernetwork/image_classification/ofa/ofa/imagenet_classification/data_providers/imagenet.py, dynast/supernetwork/image_classification/ofa/ofa/imagenet_classification/run_manager/run_manager.py, dynast/supernetwork/image_classification/ofa/ofa/utils/pytorch_utils.py, dynast/supernetwork/image_classification/ofa/ofa_interface.py, dynast/utils/datasets.py, dynast/utils/nn.py, dynast/utils/reference.py, tests/scripts/config.sh, tests/scripts/run_ofambv3_random_short.sh, tests/scripts/run_ofaresnet50_random_short.sh, tests/test_datasets.py
This change adds `test_fraction` argument to both CLI and Python interfaces. `test_fraction` accepts a floating point number in the range of `(0.0, 1.0>` which will scale the number of steps used for model evaluation on ImageNet dataset by the same factor.
Note: This has been implemented only for the ImageNet dataset.
=> Enable search with model accuracy evaluation on a fractional dataset

dynast/utils/datasets.py, tests/test_datasets.py
So far only validation with the ImageNet could have been performed. This path extends remaining image classification dataset interfaces with `fraction` parameter:
* Imagenette
* CIFAR10
=> Add fraction param to remaining image classification datasets

dynast/supernetwork/supernetwork_registry.py
Following up on the PR#34, the issue remained that the ordering of data in the CSV result file was not consistent across the DyNAS-T search.
In this particular case, while the data was saved correctly to the CSV file, it was not read properly by the predictor which caused various issues in the search results.
=> Bug: fix order of transformer-based supernet metrics

dynast/supernetwork/image_classification/ofa/ofa_interface.py
The `get_subnet` method in `OFARunner` was using improper keys for the resnet50 supernetwork.
To start with, it used `ks` which is only applicable to MobileNetV3 supernets and passed depth as it's value. Unused (`ks`) param will be ignored, but the depth, as it was not set, will take the default value of None, resulting in a limited search space.
Secondly, the depth param was set to width value. Valid values for both depth and width are the same, so there was no raised error.
=> Fix OFA interface for ResNet50

dynast/supernetwork/image_classification/ofa/ofa/utils/common_tools.py
Currently all scripts that download supernets from MIT HAN Lab's servers fail due to SSL certificate error.
This PR temporarily fixes this issue by disabling SSL check, but it should be fixed differently as soon as possible if issues with the host's SSL certificate persists.
=> Temporary workaround to HANs lab SSL issue

dynast/utils/nn.py
Image classification model was not moving model to a target device, which may result in tensor errors. This PR fixed this issue.
=> Fix: load model to a target device

dynast/dynast_manager.py, tests/test_dynast_manager.py
* `search_tactic` has a default value of `linas`; no longer required to explicitly specify.
* `num_evals` has a default value of `250`; no longer required to explicitly specify.
* `dataset_path` has a default value of None; no longer required to explicitly specify. Runs that either do not evaluate for accuracy or use custom data loaders do not need dataset to be specified.
=> Update DyNAS interface

dynast/search/search_tactic.py
Evolutionary search was wrongfully configured to evaluate a number of subnetworks equal to the number of predictions set for LINAS algorithm. This patch fixes this by using `num_evals` param instead.
=> Fix number of evaluations done in evolutionary search

dynast/cli.py
If dataset path is provided the dataloader object
will always be created. For non-accuracy-based measurments this is a redundant operation that introduces unnecessary load to the system.
=> Remove default dataset path

tests/checks/check_package.py, tests/checks/helpers.py, tests/search/__init__.py, tests/supernetwork/__init__.py, tests/supernetwork/image_classification/__init__.py, tests/supernetwork/image_classification/bootstrapnas/__init__.py, tests/supernetwork/image_classification/ofa/__init__.py, tests/supernetwork/test_classification/__init__.py, tests/utils/__init__.py
Missing `__init__.py` files are resulting in missing packages from the build PyPI wheel. To avoid this in the future this PR adds check for init files on the CI.
=> Add test for presence of `__init__.py` files in packages

.github/workflows/unit_tests.yml, CONTRIBUTING.md, LICENSE.md, README.md, SECURITY.md, requirements_test.txt
To keep Markdown files consistent and clean a new check is being added to the CI.
This check is based on the `pymarkdownlnt` library and any issues will result in validation failure of the PR.
=> Add markdown lint check to CI

dynast/search/search_tactic.py, dynast/supernetwork/supernetwork_registry.py, dynast/utils/exceptions.py, tests/search/test_search_tactic.py, tests/test_dynast_manager.py
`NASBaseConfig.verify_measurement_types` relied on hardcoded super-network types to validate specified measurement and optimization metric types. This PR modifies the method to remove hardcoded values and cross check supported measurements against the list stored in super-network registry.
=> Fix verification method for measurement types

dynast/cli.py, dynast/supernetwork/supernetwork_registry.py, tests/supernetwork/test_supernetwork_registry.py
Previously, metrics guiding the search process within the CLI interface were hardcoded. This led to manual updates in multiple locations each time a new supernetwork was introduced.
With this commit, the CLI interface will now automatically fetch possible metrics directly from the supernetwork registry, streamlining the integration of new supernetworks and reducing redundancy.
=> Auto-fetch Search Metrics in CLI from Supernetwork Registry

dynast/utils/__init__.py
Logging output in distributed search included too many redundant pieces of information.
This change reduces the clutter by replacing process name and id with `worker-<LOCAL_RANK>`.
This part of log is completely removed for a single worker.
=> Simplify logger output in distributed search

dynast/cli.py, dynast/dynast_manager.py, dynast/utils/distributed.py
With default MPI/Gloo communication timeout (30m) for certain type of optimization metrics there is a chance for the time between workers that were first and last to finish evaluating assigned configurations within a single population to cause a communication timeout. Increasing this limit prevents this issue.
=> Fix communication timeout in distributed search

dynast/search/search_tactic.py, dynast/utils/distributed.py, tests/utils/test_distributed.py
Previously only worker's result files were cleared on every search, with the main being carried over from the last search experiment (if the --result_path value was the same between the two runs). This change fixes this.
=> Clear main result file when distributed search is started.

dynast/supernetwork/image_classification/ofa_quantization/inc_quantization.py, dynast/utils/__init__.py
In some cases 3rd party library might be setting logger level after DyNAS-T's own logger is already initialized and overwrite it's settings. This PR adds method to reset log levels after initialization. This new method `reset_logger` has to be called each time after a library that overwrites logger settings is called.
=> Reset logs for 3rd party libraries

.github/workflows/unit_tests.yml
Per https://devguide.python.org/versions/ Python 3.7 has been EOL'ed and we should move to use version 3.8, at minimum.
=> Update GitHub Runner env from 3.7 to 3.8

dynast/supernetwork/image_classification/ofa/ofa_interface.py, dynast/supernetwork/image_classification/ofa_quantization/quantization_interface.py
If ran with `device='cpu'` on a machine with GPU available, OFA would force `RunManager` to use GPU. This PR fixes this issue.
=> Fix RunManager device setting in OFA

dynast/supernetwork/image_classification/ofa_quantization/inc_quantization.py, dynast/supernetwork/text_classification/bert_interface.py, requirements.txt
Older version (pre 4.36) contain several security vulnerabilities.
However, not all Transformer-based supernets are compatible with `transformers>4.27.1`. In most cases it is enough to simply set `strict=False` when loading the model.
=> Update Transformers to 4.37
